Спринт 13. Итерация 1.
SychMaf/java-shareit pull request #1
Opened 2023-06-24 13:05 UTC by SychMaf

2023-06-24 20:11 UTC, mikita95 requested changes
Все сделано очень хорошо. Оставил лишь небольшие замечания

2023-06-24 20:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@RequestHeader("X-Sharer-User-Id") Long userId,
Можно использовать примитивный long для userId, ведь это обязательный параметр

2023-06-24 20:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getOwner().equals(userId))
Можно хранить ещё одну мапу: userId -> список item , так получится "индекс" для подобных запросов и работать будет эффективнее

2023-06-24 20:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public static UserDto toUserDto(User user) {
Лучше сделать отдельные классы мапперы, так dto и модели хранения не должны знать друг про друга, так код станет менее связанным

2023-06-25 20:38 UTC, mikita95 requested changes
Все сделано хорошо. Нужно ещё немного поправить контроллеры.

2023-06-25 20:38 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody Item item) {
Контроллер не должен знать про модель хранения данных, он должен работать только с dto.

2023-06-25 20:38 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto saveUser(@Valid @RequestBody User user) {
Контроллер не должен знать про модель хранения данных, он должен работать только с dto.

2023-06-29 04:54 UTC, KirPyt reviewed
Приветствую) Я Ваш ревьюер на данную работу. Если возникнут вопросы по ревью, то пишите мне в Пачку

Указал некоторые замечания и советы по коду, предлагаю над ними поработать. Так же некоторые замечания или советы актуальны и для остальных частей кода, поэтому рекомендую обратить внимание и на другие аналогичные места в коде, чтобы всё поправить.

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +public class BookingDtoMapper {
Рекомендую подумать над тем, чтобы добавить в данный класс аннотацию `@UtilityClass`, она подчеркнет, что данный класс служебный и сделает все методы статическими, а так же добавит приватный конструктор.
Более подробно https://projectlombok.org/features/experimental/UtilityClass

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @PositiveOrZero
Валидацию стоит размещать на уровне ДТО-шек, так как именно там может прийти невалиданая информация

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +public class ErrorHandler {
Стоит добавить хендлер для отлавливания 500-ой ошибки. Надо будет ловить ошибки класса `Throwable`. Ошибка 500 определяет ошибки, вызванные разными причинами на сервере (это проверяемые и непроверяемые исключения), а ошибки `RuntimeException`, которые Вы ловите в данный момент, являются только проверяемыми.
Более подробно Вы можете почитать здесь:
https://www.baeldung.com/java-exceptions
(Раздел Exception Hierarchy)

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
В каждый хендлер стоит добавить логирование стек трейса

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.saveItem(itemDto, userId);
Рекомендую добавить в каждый метод контроллера логирование входящего запроса

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody Map<String, Object> updates) {
Здесь ловим ДТО-шку, вместо мапы

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +public class ItemDtoMapper {
Аналогично, можно поставить аннотацию @UtilityClass

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        for (String key : updates.keySet()) {
Здесь логику тоже надо будет поправить, когда поменяете мапу в контроллере на ДТО-шку

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                        && item.getAvailable()))
Рекомендую проверять условие доступности самым первым, так как его проверить быстрее всего

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoMapper.java
> +public class ItemRequestDtoMapper {
Аналогично, можно поставить аннотацию @UtilityClass

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                              @Valid @RequestBody Map<String, Object> updates) {
Здесь ловим ДТО-шку вместо мапы

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
Аналогично, можно поставить аннотацию @UtilityClass

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/validator/ItemFieldsValidator.java
> +@Service
Предлагаю делать валидировать статическими, чтобы не делать из них компоненты спринга, так как они нужны только как служебные классы

2023-06-29 04:54 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/validator/UserFieldsValidator.java
> +@Service
Аналогично, можно не делать данный служебный класс компонентом

2023-06-29 19:28 UTC, KirPyt reviewed
В целом всё очень хорошо, Вы много поработали)
Указал один момент по поводу утилитарного класса, рекомендую иметь в виду его на будущее

Ваш проект зачтён

2023-06-29 19:28 UTC, KirPyt commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
Можно не ставить ключевое слово `static`, так как за Вас это делает аннотация `@UtilityClass`

2023-07-01 15:03 UTC, merged